### ISSUE TITLE
Not working windows 10

### ISSUE THREAD

**Issue by jimbobshazham** [78Alpha/BMPMan#3]
Went to use this as you described in documentation and got this when I tried to use it.

> DEBUG: Creating Working Directories...
> DEBUG: Running Agree Function
> DEBUG: Data Directory Agree | C:\Users\smelly/BMPMan/
> DEBUG: Loading Agreement Form...
> DEBUG: Global Settings Loading...
> DEBUG: Global Settings Loaded!
> DEBUG: Data Directory Core | C:\Users\smelly/BMPMan/
> DEBUG: Attempting To Load Custom Font...
> DEBUG: Event | make
> DEBUG: Values | ['USE_DEFAULT', 'USE_DEFAULT']
> DEBUG: List | ['jellyfish-20-mbps-hd-h264.mkv']
> DEBUG: List | ['jellyfish-20-mbps-hd-h264.mkv']
> DEBUG: Length Of List | 
> DEBUG: Thread Count Set | 6
> DEBUG: Process Start!
> DEBUG: Base = b'BM\xd2\xe4\xde\x02\x00\x00\x00\x00z\x00\x00\x00l\x00\x00\x007\x13\x00\x00\xbf\x0c\x00\x00\x01\x00\x18\x00\x00\x00\x00\x00X\xe4\xde\x02\x13\x0b\x00\x00\x13\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00BGRs\x00\x00\x00\x00\x00\x00'
> DEBUG: Keys | []
> DEBUG: Hashing Start...
> DEBUG: Hashing End!
> DEBUG: File Size | 74754816
> DEBUG: Out_Num_Start = 1
> DEBUG: Out Remainder | 26754816
> DEBUG: Out_Rem | {}26754816 Bytes
> DEBUG: Out_Num_End | 2
> DEBUG: Out Number | 2
> DEBUG: File In Use | <_io.BufferedReader name='Input_Data/jellyfish-20-mbps-hd-h264.mkv'>
> DEBUG: Chunk Called On File | <_io.BufferedReader name='Input_Data/jellyfish-20-mbps-hd-h264.mkv'>
> DEBUG: Name Of Used File | Input_Data/jellyfish-20-mbps-hd-h264.mkv
> DEBUG: Size Of File | 74754816
> DEBUG: Out Num | 1
> DEBUG: Out Rem | 26754816
> DEBUG: Out Rem Greater Than Zero!
> DEBUG: Out Num Extended!
> DEBUG: Processing File By Chunks...
> DEBUG: Data Yielded To Parent Function!
> DEBUG: Current | 0
> DEBUG: Working With File | jellyfish-20-mbps-hd-h264.mkv
> DEBUG: Expected Output Files | 2
> DEBUG: Progress Bar Started!
> DEBUG: Name Dig Not At Limit | No User Cancellation
> DEBUG: Name Dig | 0
> DEBUG: Buffer Flushed to Output_Images/jellyfish-20-mbps-hd-h264.mkv-0.bmp!
> DEBUG: Buffer Size | 48000000
> DEBUG: File Name | jellyfish-20-mbps-hd-h264.mkv
> DEBUG: Header Bytes Written!
> DEBUG: Buffer Bytes Written!
> DEBUG: File Data Written!
> DEBUG: Data Yielded To Parent Function!
> DEBUG: Current | 0
> DEBUG: Working With File | jellyfish-20-mbps-hd-h264.mkv
> DEBUG: Expected Output Files | 2
> DEBUG: Progress Bar Started!
> DEBUG: Name Dig Not At Limit | No User Cancellation
> DEBUG: Name Dig | 1
> DEBUG: Buffer Flushed to Output_Images/jellyfish-20-mbps-hd-h264.mkv-1.bmp!
> DEBUG: Buffer Size | 26754816
> DEBUG: File Name | jellyfish-20-mbps-hd-h264.mkv
> DEBUG: Header Bytes Written!
> DEBUG: Buffer Bytes Written!
> DEBUG: File Data Written!
> DEBUG: Name Dig | 2
> DEBUG: Loading Completion Popup...
> DEBUG: Process Should Halt!
> DEBUG: Files In Out Len | ['jellyfish-20-mbps-hd-h264.mkv-0.bmp', 'jellyfish-20-mbps-hd-h264.mkv-1.bmp']
> DEBUG: Hashing Images...
> DEBUG: Name | jellyfish-20-mbps-hd-h264.mkv-0.bmp
> DEBUG: Start Hash Function...
> DEBUG: Loading Hashes File...
> DEBUG: Hashing Choice Set...
> DEBUG: Breaking File Into Chunks...

Not sure what is going on but I am left with a bunch of .BMP files that this program can't do anything with so I'm assuming it spat out a lot of garbage.

**Comment by 78Alpha** [comment]
Whoa, that is a version I don't have around anymore. It looks around 1.5.6 though...

Just updated to 2.0.1, adds in hashing to verify that the images and output are like the original. I'll start working on making an exe and testing myself.

**Comment by 78Alpha** [comment]
@jimbobshazham Released the 2.0.1 update, and it has a windows binary that I have tested out. Input and output hashes passed verification, so everything should work.

**Comment by jimbobshazham** [comment]
Great I'll give it a whirl
